import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("screen");

export const styles = StyleSheet.create({
  textBoxWrapper: {
    width: "84%",
    alignSelf: "center",
    flexDirection: "row",
    height: 55,
    backgroundColor: "#FFFFFF50",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    alignItems: "center",
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  textBoxStyle: {
    width: "75%",
    height: 60,
    fontSize: 18,
    marginLeft: 10,
    fontFamily: "Quicksand-Medium",
    letterSpacing: 1.5,
    color: "#FFFFFF",
  },
  sMWrapper: {
    width: "80%",
    position: "absolute",
    bottom: 100,
  },
  sMBody: {
    width: "80%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
    padding: 5,
    alignSelf: "center",
  },
  googleImage: { width: 50, height: 50 },
  facebookImage: { width: 40, height: 40 },
  appleImage: { width: 50, height: 50 },
  rememberMe: {
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginVertical: 5,
    alignSelf: "center",
  },
  rememberMeText: {
    fontFamily: "Quicksand-Medium",
    color: "#FFFFFF",
    fontSize: 16,
    marginLeft: 5,
  },
  notMember: {
    fontFamily: "Quicksand-SemiBold",
    color: "#FFFFFF",
    fontSize: 16,
    textAlign: "right",
  },
  signUpWrapper: {
    width: "82%",
    alignSelf: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    marginVertical: 10,
  },
  loginInfo: {
    flexDirection: "row",
    alignItems: "center",
    width: "75%",
    alignSelf: "center",
    justifyContent: "flex-start",
  },
  loginText: {
    fontFamily: "Quicksand-Medium",
    fontSize: 13,
    color: "#FFFFFF",
    marginLeft: 5,
  },
  lottieWrapper: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  bodyWrapper: {
    width: "90%",
    height: height - 380,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  lottieLogin: {
    width: 180,
    height: 180,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  signInBox: {
    width: "85%",
    justifyContent: "center",
    alignItems: "center",
  },
  signInText: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Bold",
    fontSize: 34,
  },
  buttonStyle: {
    backgroundColor: "#FFC000",
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    width: "84%",
    borderRadius: 30,
    marginVertical: 10,
  },
  buttonStyleText: {
    fontFamily: "Quicksand-SemiBold",
    color: "#FFFFFF",
    fontSize: 24,
  },
  phoneInputContainer: {
    width: "90%",
    height: height - 380,
    borderRadius: 10,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  phoneInputWrapper: {
    width: "90%",
    alignSelf: "center",
    justifyContent: "space-between",
    height: height - 400,
  },
  phoneLottie: {
    width: 170,
    height: 170,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 40,
  },
  tickLottie: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 40,
  },
  enterMobileNumber: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 22,
  },
  confirmText: {
    color: "#FFC000",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 16,
    marginVertical: 10,
  },
  phoneContainer: {
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    paddingHorizontal: 5,
    width: "100%",
  },
  phoneTextContainer: {
    backgroundColor: "transparent",
  },
  phoneTextInput: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 30,
  },
  phoneCodeText: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 30,
  },
  oopsError: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 14,
    paddingHorizontal: 5,
    marginVertical: 10,
  },
  continueButton: {
    width: "100%",
    alignSelf: "center",
    backgroundColor: "#FFC000",
    justifyContent: "center",
    alignItems: "center",
    height: 60,
    borderRadius: 10,
    marginVertical: 10,
  },
  goBack: {
    width: "46%",
    alignSelf: "center",
    backgroundColor: "#A4A4A4",
    justifyContent: "center",
    alignItems: "center",
    height: 60,
    borderRadius: 10,
    marginVertical: 10,
  },
  reSend: {
    width: "46%",
    alignSelf: "center",
    backgroundColor: "#FFC000",
    justifyContent: "center",
    alignItems: "center",
    height: 60,
    borderRadius: 10,
    marginVertical: 10,
  },
  continueText: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 26,
  },
  goBackText: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 26,
  },
  phoneNumberWrapper: {
    width: "100%",
    alignSelf: "center",
    height: 80,
    overflow: "hidden",
  },
  goBackWrapper: { flexDirection: "row", justifyContent: "space-between" },
  addressHeaderWrapper: {
    backgroundColor: "transparent",
    height: 70,
    width: "70%",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "flex-end",
  },
  addressText: {
    fontFamily: "Quicksand-SemiBold",
    color: "#232023",
    fontSize: 22,
  },
  saveButton: {
    color: "#D22B2B",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 20,
  },
  typeBox: {
    borderWidth: 1,
    borderColor: "#4A4A4A",
    padding: 3,
    borderRadius: 6,
    width: 50,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
    height: 25,
  },
  typeText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 12,
    color: "#4A4A4A",
  },
  panelMain: { width: "100%", marginVertical: 5 },
  savesText: {
    fontFamily: "Quicksand-Regular",
    fontSize: 14,
    color: "#4A4A4A",
  },
  buttonsMain: {
    marginVertical: 10,
    width: "100%",
    flexDirection: "row",
  },
  label: {
    fontFamily: "Quicksand-Regular",
    fontSize: 14,
    color: "#4A4A4A",
    marginVertical: 5,
  },
  inputBox: {
    width: "100%",
    borderWidth: 0.5,
    borderColor: "#4A4A4A",
    borderRadius: 7,
    height: 45,
    fontFamily: "Quicksand-Medium",
    fontSize: 16,
    paddingHorizontal: 10,
  },
  addressTypeInput: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  addressTypeEntry: {
    borderWidth: 0.5,
    borderColor: "#A4A4A4",
    height: 25,
    borderRadius: 6,
    padding: 5,
    fontSize: 12,
    width: "78%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addressTypeSave: {
    height: 25,
    padding: 5,
    backgroundColor: "#FFC000",
    width: "20%",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  addressTypeSaveText: { color: "#FFFFFF", fontFamily: "Quicksand-SemiBold" },
  privacyPolicySection: {
    width: "100%",
    position: "absolute",
    bottom: 45,
    justifyContent: "center",
    alignItems: "center",
  },
  continuePolicyText: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 15,
  },
  clickableButton: {
    width: "40%",
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 7,
  },
  privacyPolicy: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 12,
  },
  terms: {
    color: "#FFFFFF",
    fontFamily: "Quicksand-Medium",
    fontSize: 12,
  },
});
